apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: vyktwc61u-python 
  janus-idp.io/tekton: vyktwc61u-python
  backstage.io/kubernetes-id: vyktwc61u-python
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: vyktwc61u-python
resources: 
- application-dev.yaml 
- application-stage.yaml 
- application-prod.yaml  